version: '3.8'
services:
  db:
    container_name: paperless_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: paperless
    ports:
      - "1433:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"

  rabbitmq:
    container_name: rabbitmq_container
    image: "rabbitmq:management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123


  es-node01:
    container_name: es-node01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    restart: always
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
  
  kib-01:
    container_name: kib-01
    image: docker.elastic.co/kibana/kibana:8.11.3
    restart: always
    networks:
      - elastic
    ports:
      - 5601:5601
  
networks:
    elastic:
      name: elastic